export const projectsInfo = [
  {
    name: 'Libre mercado',
    technologies: [
      'React',
      'Node.js',
      'Express',
      'MongoDB',
      'Redux',
      'Responsive',
      'Javascript',
      'HTML & CSS',
    ],
    about:
      'La idea de este proyecto fue hacer un eCommerce site mientras copiaba el estilo de una página web reconocida, y que mejor opción que mercado libre.',
    features: [
      'Registro e inicio de sesión',
      'Autenticación con token usando JSON Web Tokens',
      'Verificación de email mediante código',
      'Registro de domicilio',
      'Cambio de contraseña y email',
      'Vender y comprar productos',
      'Sistema de favoritos, notificaciones e historial',
      'Posibilidad de hacer preguntas al vendedor de un producto',
      'Posibilidad de valorar la compra',
      'Sección de favoritos, historial, compras, preguntas, publicaciones, notificaciones, ventas y datos personales',
      'Categorías para los productos',
      'Búsqueda con filtros',
    ],
    gif: 'https://media.giphy.com/media/6Jp7gPuCJ4MdAAaRub/giphy.gif',
    backgroundColor: '#9ED9D5',
    color: 'black',
    demo: 'https://libre-mercado1.herokuapp.com/',
    code: 'https://github.com/PeyonManuel/mercado-libre-clone',
  },
  {
    name: 'Moviezz',
    technologies: ['React', 'Javascript', 'HTML & CSS'],
    about:
      'Directorio de películas utilizando The movie database API.\n El objetivo fue crear un directorio utilizando las funcionalidades más importantes de la API y hacer un diseño propio utilizando inspiraciones en otros directorios de películas populares.',
    features: [
      'Listado de películas, series y personas más populares del momento',
      'Búsqueda con sugerencias automáticas de películas, series y personas',
      'Sitio sobre cada película con información general, reparto, detalles, reseñas y películas similares o la collección de la película',
      'Sitio sobre cada serie con información general, reparto, detalles, reseñas y series similares',
      'Sitio sobre cada persona con biografía, detalles, filmografía en orden por popularidad del momento y filmografía categorizada en tipo, año y detalles como cantidad de episodios o rol',
    ],
    gif: 'https://media.giphy.com/media/lYTUU3yMtVZYVvC3ag/giphy.gif',
    backgroundColor: '#14393F',
    color: 'white',
    demo: 'https://moviezzz-datab.netlify.app/',
    code: 'https://github.com/PeyonManuel/movie-project',
  },
  {
    name: "Jack's Lounge",
    technologies: ['React', 'Javascript', 'HTML & CSS'],
    about:
      "Product landing page para Jack's Lounge que es un restobar con cafeteria.",
    features: [
      'Imagen de presentación con efecto parallax',
      'Descripción del lugar con imagenes',
      'Animaciones para la sección About',
      'Desplamiento entre diferentes secciones',
      'Exhibición de carta de cafeteria',
      'Exhibición de carta de restaurant',
    ],
    gif: 'https://media.giphy.com/media/xnWejodKxeAGL0iK84/giphy.gif',
    backgroundColor: '#d77815',
    color: 'white',
    demo: 'https://jackslounge.netlify.app/',
    code: 'https://github.com/PeyonManuel/Jack-s-longue-landing-page',
  },
  {
    name: 'Recipe finder',
    technologies: ['React', 'Javascript', 'HTML & CSS'],
    about:
      'App donde al ingresar ingredientes en la barra de busqueda, devuelve una lista de recetas utilizando estos ingredientes utilizando spoonacular recipe API.',
    features: [
      'Búsqueda con sugerencias automáticas de ingredientes',
      'Listado de recetas según los ingredientes ingresados',
      'Las recetas especifican que ingredientes utilizan y cuales serian aún necesarios',
    ],
    gif: 'https://media.giphy.com/media/KWkoAQMaSLcIWRNf13/giphy.gif',
    backgroundColor: '#74cd4d',
    color: 'white',
    demo: 'https://recipe-finder-mp.netlify.app/',
    code: 'https://github.com/PeyonManuel/recipe-finder',
  },
  {
    name: 'Drum machine',
    technologies: ['React', 'Javascript', 'HTML & CSS'],
    about:
      'Batería digital que genera distintos sonidos dependiendo la tecla y batería seleccionada.\n Creada durante el curso de Front End Development Libraries de freeCodeCamp.',
    features: [
      'Reproducir sonidos al clickear una tecla con el mouse o con la correspondiente tecla del teclado',
      'Dos tipos de baterías que ofrecen distintos sonidos para las teclas',
      'Prender y apagar la batería',
      'Cambiar el volumen de la batería',
    ],
    gif: 'https://media.giphy.com/media/fH2rsnpKptdJVcyjf8/giphy.gif',
    backgroundColor: '#bd1534',
    color: 'white',
    demo: 'https://codepen.io/Umim/full/bGpOJpP',
    code: 'https://codepen.io/Umim/pen/bGpOJpP',
  },
  {
    name: 'Javascript calculator',
    technologies: ['React', 'Javascript', 'HTML & CSS'],
    about:
      'Calculadora científica digital\n Creada durante el curso de Front End Development Libraries de freeCodeCamp.',
    features: [
      'Calcular sumas, restas, multiplicaciones y diviciones con numeros reales y mostrar los resultados en el monitor',
      'Calcular operaciones combinadas',
      'Precision de al menos 4 decimales',
    ],
    gif: 'https://media.giphy.com/media/RnoSYn52Sius9mhdrj/giphy.gif',
    backgroundColor: '#ecb726',
    color: 'black',
    demo: 'https://codepen.io/Umim/full/ZEWPgbg',
    code: 'https://codepen.io/Umim/pen/ZEWPgbg',
  },
  {
    name: 'Portfolio',
    technologies: ['React', 'Javascript', 'HTML & CSS'],
    about:
      'Portafolio digital donde presentarme, dar mi contacto y mostrar mis mejores proyectos.',
    features: [],
    gif: 'https://media.giphy.com/media/a4J6IVaKeUYM8S3ZnX/giphy.gif',
    backgroundColor: 'black',
    color: 'white',
    demo: 'none',
    code: 'https://github.com/PeyonManuel/portfolio',
  },
];
